# Site settings
title:          Blog
description:    "My personal blog"
url:            "http://leonardthiele.com"
permalink: /article/:slug/
baseurl: ""

# Author
author:
  name:         Leonard Thiele
  url:          https://leonardthiele.com
  email:        leonardthiele@gmail.com

# Build settings
markdown:       kramdown

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  pages:
    output: true
    permalink: /:name/

# Assets
sass:
  style: :compressed
  sass_dir: assets/css

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-contentblocks
